config/routes.rb
Rails.application.routes.draw do

  resources :destinations, :posts
  post '/post/:id/edit' => "posts#edit", as: "edit_post_button"

  resources :pins, only: [:edit, :update]
  get '/destinations/:id/posts/new' => "posts#new"
  post '/users/:id/pins' => "pins#users"

  resources :posts, only: [:show] do
    resources :pins, only: [:create, :index]
  end


  get "/users/:id/pins" => "pins#index", as: "user_pins"
  post "/posts/:post_id/pins" => "pins#create", as: "user_post_pins"
  get "/posts/:type_of/inspiration" => "posts#type", as: "post_type"



  get '/users' => "users#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/:id' => "users#show", as: "user"
  root to: "application#home"
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :pins, through: :posts
  has_many :users, through: :posts
  validates :name, presence: :true
  serialize :pictures




  def self.search(search)
    where("name LIKE ?", "%#{search}%").first
  end










end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  scope :active_pins, -> (current_user) { where(status: true, user_id: current_user.id )}
  scope :inactive_pins, -> (current_user) { where(status: false, user_id: current_user.id )}






end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  belongs_to :destination
  has_many :pins, dependent: :destroy
  validates :title, :flight, :total_cost, :diet, :climate, :content, :car_rental, presence: true
  validates :avatar, presence: true, allow_blank: false
  validate :must_have_a_destination
  scope :all_posts, -> {Post.order(id: :desc)}
  scope :inspiration_posts, -> (type) {where(vacation_type: type) }

  def must_have_a_destination
    if !self.destination_id
      self.errors.messages[:bad_destination] = ["Please choose only one destination"]
    end
  end


  def destination_attributes=(destination_attributes)
    if self.destination && !destination_attributes["name"].empty?
      self.destination = nil
    end

    if !self.destination && !destination_attributes["name"].empty?
      destination_name = destination_attributes["name"].split.map(&:capitalize)*' '
      self.destination = Destination.find_or_create_by(name: destination_name)
    end

    if self.destination && destination_attributes["name"].empty?
      self.destination = Destination.find_by(id: self.destination.id)
    end
  end
  #if there is a destinaton id and the name key is provided in the destinations_attribute params
  #then we set the destination to nil for the post object because we do not want two destinations entered.
  #this way now the post will error out because a destiantion is not provided

  #in the nest condition is the destination was not choosen from the options provided and the destination name is provided then we find or create the destination by name and associate it to the post.

  #else of course a destination is choosen from the options and the post now is assigned to the choosen destination.


  def destination_attributes
    self.destination
  end




end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :destinations, through: :posts



  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end


  def post_pins
    arr = []
    self.posts.each do |post|
      arr << post.pins.count
    end
      arr.sum
  end






















end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end



  def home
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end

  private

  def check_logged_in?
    if !user_signed_in?
      redirect_to "/"
      flash[:notice] = "Please Log in or Sign Up to Navigate Site"
    end
  end





end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :find_destination



  def index
    render json: Destination.all
  end

  def show
    @des = Destination.find_by(id: params[:id])
    respond_to do |f|
        f.html { render :show }
        f.json { render json: @des, adapter: :json}
      end
  end


  def find_destination
    @destination = Destination.find_by(id: params[:id])
  end



end

app/controllers/pins_controller.rb
class PinsController < ApplicationController



  def create
    post = Post.find_by(id: params[:post_id])
    post.pins.create(user_id: current_user.id)
    redirect_to post_path(post)
  end

  def index
    user = User.find_by(id: params[:id])
    @pins = user.pins
    @active_pins = Pin.active_pins(current_user)
    @inactive_pins = Pin.inactive_pins(current_user)
    respond_to do |f|
        f.html { render :index }
        f.json { render json: @pins}
      end
  end


  def edit
    @pin = Pin.find_by(id: params[:id])
    @pin.update(status: false)
    flash[:notice] = "You have visited #{@pin.post.destination.name}"
    redirect_to user_pins_path(current_user)
  end



  def update
    @pin = Pin.find_by(id: params[:id])
    @pin.update(status: false)
    flash[:notice] = "You have visited #{@pin.post.destination.name}"
  end









end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all_posts
    respond_to do |f|
        f.html { render :index }
        f.json { render json: @posts }
      end
  end

  def new
    @post = Post.new
    @destinations = Destination.all
    respond_to do |f|
        f.html { render :new }
        f.json { render :new}
      end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render json: @post
    else
      render json: @post.errors.full_messages, status: 422
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    current_user.pins.map do |pin|
      @pin = (pin.post_id == @post.id)
    end
    if @pin
      flash[:notice] = "You Have Pinned This Post"
    end
    respond_to do |f|
        f.html { render :show }
        f.json { render json: @post, adapter: :json}
      end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @destination = @post.destination
  end

  def update
    @post = Post.find_by(id: params[:id])
      if @post.update(post_params)
        redirect_to user_path(current_user)
      else
        @errors = @post.errors.full_messages
      render :edit
    end
  end

  def type
    @title = params[:type_of]
    if params[:type_of] === "Wildlife and Safari"
      @pic = "tanzania-safari-tours-1400x575.jpg"
    elsif params[:type_of] === "Honeymoon and Romantic"
      @pic = "324636-istock-maldives-honeymoon.jpg"
    elsif params[:type_of] === "Family"
      @pic = "9c31bf_92c2f1bc4b884646b4f624a1a1481f8e.jpg_srz_1799_1196_85_22_0.50_1.20_0.jpg"
    elsif params[:type_of] === "Rainforest and Jungles"
      @pic = "villa-blanca-cloud-forest-costa-rica-zipline-DSC01931-ret-small2.jpg"
    elsif params[:type_of] === "Beaches"
      @pic = "D227-hero-fiji-yasawa-island-private-beach-2000x837.jpg"
    elsif params[:type_of] === "Road Trip"
      @pic = "iStock_000038250840Large_0.jpg"
    end
    @posts = Post.inspiration_posts(params[:type_of])
    render :inspiration
  end


  private

  def post_params
    params.require(:post).permit(:title, :vacation_type, :total_cost, :flight, :climate, :car_rental, :diet, :content, :user_id, :avatar, :destination_id, :destination_attributes => [:name])
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user     
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end


  def show

  @user = User.find_by(id: params[:id])
  respond_to do |f|
      f.html { render :show }
      f.json { render json: @user}
    end
  end

  def create
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/destinations/edit.html.erb
<%= render partial: "destinations/form", locals: {destination: @destination, post: @post} %>

app/views/destinations/new.html.erb
<%= render partial: "destinations/form", locals: {destination: @destination, post: @post} %>

app/views/destinations/show.html.erb
<div class="heroSlideShow" id="<%=@des.id %>">
  <div class="fade-group">
    <h2></h2>
  </div>
</div>

<div class="segment"></div>

<h2 class="show-page-title">Experiences In <%= @des.name %></h2>
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>

<div class="show_cards">
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul>
    <li>About Us</li>
    <li>Careers</li>
    <li>Contact Us</li>
    <li>Terms and Conditions</li>
    <li>Privacy Policy</li>

    <i class="facebook square icon"></i>
    <i class="tumblr icon"></i>
    <i class="instagram icon"></i>
  </ul>
</div>

app/views/layouts/_navigation.html.erb
<% if !user_signed_in? %>
<div class="root_page_content">
  <div class="travel_quote">
    <h1>TravelBook</h1>
      <div class="quote">
        <h2 class>The world is a book, and those </h2>
        <h2> who do not travel read</h2>
        <h2>only a page</h2>
      </div>
  </div>

  <div class="login-box">
    <a href="/users/sign_in" class="sign_in"><button class="user_sign_up" background-color:"transparent">Explore</button></a>
  </div>
</div>
<%end%>

<%if user_signed_in? %>
<div id="MenuHolder">
  <nav>
    <ul>
      <li><a href="/users/<%=current_user.id%>">Home</a></li>
      <li><a href="/posts" id="blogs">Blogs</a></li>
      <li><a>Inspiration</a>
        <ul class="nav_selection">
          <li><%=link_to "Wildlife and Safari", post_type_path("Wildlife and Safari")%></li>
          <li><%=link_to "Honeymoon and Romantic", post_type_path("Honeymoon and Romantic")%></li>
          <li><%=link_to "Rainforest and Jungles", post_type_path("Rainforest and Jungles")%></li>
          <li><%=link_to "Beaches", post_type_path("Beaches")%></li>
          <li><%=link_to "Road Trip", post_type_path("Road Trip")%></li>
          <li><%=link_to "Family", post_type_path("Family")%></li>
        </ul>
      </li>
     <li><a id="nested">Publish</a></li>
      <li><a id="my-pins" href="/users/<%=current_user.id%>/pins">Pins</a></li>
    </ul>
  </nav>
  <div class="ui search">
    <div class="ui icon input">
      <input class="prompt" type="text" placeholder="Search Destination..." onFocus=makeDestinationCall()>
      <i class="search icon"></i>
    </div>
    <div class="results"></div>
  </div>
    <div id="log_Out">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "ui item"%>
    </div>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Travelbook</title>
    <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Tangerine">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.6/semantic.min.css"/>
    <%= javascript_include_tag "application" %>
  
    <%= csrf_meta_tags %>
  </head>

  <body id="<%=current_user.id if current_user%>">
    <div id="page_wrap1">
    <%= render 'layouts/navigation' %>

    <%= yield %>

    <!-- <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %> -->
      <!-- <div id="footer">Footer will always be at the bottom</div> -->
        <%= render 'layouts/footer' %>
      <script src="https://cdn.jsdelivr.net/semantic-ui/2.2.6/semantic.min.js"></script>
  </div>
  </body>
</html>

app/views/pins/index.html.erb
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>

<% if @active_pins.length > 0 %>
  <h2 class="pin_title">Pinned Destinations</h2>
  <div class="ui middle aligned divided list">
    <% @active_pins.each do |pin| %>
      <div class="item">
        <div class="right floated content">
          <a href="/pins/<%=pin.id%>/edit"><div class="ui button">Visited</div></a>
        </div>
      <div class="pin_post_content">
      <%= pin.post.title %>
      </div>
    </div>
   <%end%>
  </div>
<%end%>

<%if @active_pins.length == 0 && @inactive_pins.length == 0 %>
  <div class="page_length">
  </div>
<%end%>

<% if @inactive_pins.length > 0 %>
  <h2 class="pin_title">Visited Destinations</h2>
  <div class="ui middle aligned divided list">
    <% @inactive_pins.each do |pin|%>
      <div class="item">
        <div class="right floated content">
          <a href="/posts/<%=pin.post.id%>"><div class="ui button">Read Post</div></a>
        </div>
      <div class="pin_post_content">
        <%= pin.post.title %>
        <br></br>
      </div>
      <%end%>
  </div>
<%end%>

app/views/posts/_form.html.erb
<div class="ui modal">
  <div class="header">Share an Experience</div>
    <div class="form_content">
    <%= form_for post do |f| %>
       <%= f.hidden_field :user_id, :value => current_user.id %>
       <%= f.label "Select a Destination"%>
       <%= f.collection_select :destination_id, Destination.all, :id, :name, :include_blank => true %>

       <%= f.fields_for :destination, post.build_destination do |des|%>
         <%= des.label "Or Enter Destination Name" %>
         <%= des.text_field :name, class: "custom_field" %>
       <%end%>
       <br></br>
       <label>Type of Trip</label>
       <br>
        <select id="vacationType" name="post[vacation_type]">
          <option value=""></option>
          <option value="Beaches">Beach</option>
          <option value="Honeymoon Romantic">Honeymoon Romantic</option>
          <option value="Wildlife and Safari">WildLife and Safari</option>
          <option value="Wildlife and Safari">Rainforest and Jungles</option>
          <option value="Wildlife and Safari">Road Trip</option>
          <option value="Wildlife and Safari">Family</option>
          <option value="Wildlife and Safari">Cruise</option>
        </select>
      <br></br>
      <label>Title</label>
       <%=f.text_field :title, class: "custom_field" %>
       <br><br>
       <label>Total Cost of Trip</label>
       <%= f.text_field :total_cost, class: "custom_field" %>
       <br></br>
       Please Rate the Following from 1-5
       <br>
       <br>
        How was your flights? <%=f.radio_button :flight, 1%> 1 <%=f.radio_button :flight, 2%> 2 <%=f.radio_button :flight, 3%> 3 <%=f.radio_button :flight, 4%> 4 <%=f.radio_button :flight, 5%> 5
        <br>
        How great was the climate? <%=f.radio_button :climate, 1%> 1 <%=f.radio_button :climate, 2%> 2 <%=f.radio_button :climate, 3%> 3 <%=f.radio_button :climate, 4%> 4 <%=f.radio_button :climate, 5%> 5
        <br>
        Was the car rental services Awesome? <%=f.radio_button :car_rental, "1"%> 1 <%=f.radio_button :car_rental, 2%> 2 <%=f.radio_button :car_rental, 3%> 3 <%=f.radio_button :car_rental, 4%> 4 <%=f.radio_button :car_rental, 5%> 5
        <br>
        How amazing was the food? <%=f.radio_button :diet, "1"%> 1 <%=f.radio_button :diet, 2%> 2 <%=f.radio_button :diet, 3%> 3 <%=f.radio_button :diet, 4%> 4 <%=f.radio_button :diet, 5%> 5
        <br></br>

        <label>content</label>
        <br>
       <%=f.text_area :content %>
       <br><br>
       <%= f.file_field :avatar %>
        <br></br>
        <%=f.submit class: "ui button", id: "submit_form"%>
    <%end%>
    </div>

  <div class="error">
    <ul class="list"></ul>
  </div>

</div>

app/views/posts/edit.html.erb
<div class="edit">
<h1 class="form_title">Share an Experience</h1>
  <input id="hidden" style="display: none;">

  <%= form_for @post do |f| %>
    <div class="input_options">
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.label "Select a Destination"%>
        <%= f.collection_select :destination_id, Destination.all, :id, :name, :include_blank => true %>

        <%= f.fields_for :destination, @destination do |des|%>
          <%= des.label "Or Enter Destination Name" %>
          <%= des.text_field :name, class: "custom_field"%>
        <%end%>
        <br></br>

        <label>Type of Trip</label>
          <br>
        <select id="vacationType" name="post[vacation_type]">
          <option value=""></option>
          <option value="Beaches">Beach</option>
          <option value="Honeymoon Romantic">Honeymoon Romantic</option>
          <option value="Wildlife and Safari">WildLife and Safari</option>
          <option value="Rainforest and Jungle">Rainforest and Jungles</option>
          <option value="Road Trip">Road Trip</option>
          <option value="Family">Family</option>
          <option value="Cruise">Cruise</option>
        </select>
        <br></br>

        <label>Title</label>
        <br>
        <%=f.text_field :title, class: "custom_field"%>
        <br><br>
        <label>Cost Of Trip</label>
        <br>
        <%= f.text_field :total_cost, class: "custom_field" %>
        <br></br>
        Please Rate the Following from 1-5
        <br>
        How was your flights? <%=f.radio_button :flight, 1%> 1 <%=f.radio_button :flight, 2%> 2 <%=f.radio_button :flight, 3%> 3 <%=f.radio_button :flight, 4%> 4 <%=f.radio_button :flight, 5%> 5
        <br>
        How great was the climate? <%=f.radio_button :climate, 1%> 1 <%=f.radio_button :climate, 2%> 2 <%=f.radio_button :climate, 3%> 3 <%=f.radio_button :climate, 4%> 4 <%=f.radio_button :climate, 5%> 5
        <br>
        Was the car rental services Awesome? <%=f.radio_button :car_rental, "1"%> 1 <%=f.radio_button :car_rental, 2%> 2 <%=f.radio_button :car_rental, 3%> 3 <%=f.radio_button :car_rental, 4%> 4 <%=f.radio_button :car_rental, 5%> 5
        <br>
        How amazing was the food? <%=f.radio_button :diet, "1"%> 1 <%=f.radio_button :diet, 2%> 2 <%=f.radio_button :diet, 3%> 3 <%=f.radio_button :diet, 4%> 4 <%=f.radio_button :diet, 5%> 5
        <br></br>

        <label>Content</label>
        <br>
        <%=f.text_area :content %>
        <br></br>
        <%= f.file_field :avatar %>
        <br></br>
        <%=f.submit class: "ui button"%>
      <%end%>
    </div>
  </div>

  <div class="error">
    <ul class="list">
      <% if @errors %>
        <% @errors.each do |e| %>
          <li><%= e %></li>
        <%end%>
      <%end%>
      </ul>
  </div>

app/views/posts/index.html.erb
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>
<div class="all-posts">


</div>

app/views/posts/inspiration.erb
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>
<div class="inspiration_page">
<div class="inspiration_image" style="background-image: url(<%= asset_path @pic %>)">
  <h2 class="inspiration_title"><%=@title%></h2>
  </div>
  <h2 class="show-page-title">Plan Your Next Trip</h2>


<% if @posts.length > 0 %>
<div class="show_cards">
  <%@posts.each do |p| %>
  <% date = p.created_at.strftime("%d %b. %Y") %>
    <div class="img" style="background-image: url(<%=p.avatar.url%>)"><a   href="/posts/<%=p.id%>"><p class="card_date"><%=date%></p><h3 class="card_title1"><%=p.title%></h3></a>
    </div>
  <%end%>
</div>
<%end %>
</div>

app/views/posts/new.html.erb
<%= render partial: "posts/form", locals: {post: @post, destination: Destination.new}%>

app/views/posts/show.html.erb
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>

<div class="post_show">
  <h1><%=@post.title%></h1>
  <span><%=@post.destination.name%></span>
      <br></br>
    <div class="ratings">
      Car Rental <div class="ui star rating" data-rating='<%=@post.car_rental%>'>hi</div>
      <br>
      Flight <div class="ui star rating" data-rating='<%=@post.flight%>'></div>
      <br>
      Diet <div class="ui star rating" data-rating='<%=@post.diet%>'></div>
      <br>
      Climate <div class="ui star rating" data-rating='<%=@post.climate%>'></div>
    </div>
  <div class="showpage_image" style="background-image: url(<%=@post.avatar%>)"></div>

  <% p = @post.content.split("\n")%>
  <% p.each do |e| %>
    <p><%=e%></p>
  <%end%>

  <%if current_user.id == @post.user_id %>
    <a class="update_post" id='<%=@post.id%>' href="/posts/<%=@post.id%>/edit">Update Post</a>
  <%end%>

  <% if @post.user_id != current_user.id %>
    <% if !@pin %>
      <!-- <a href="/posts/<%=@post.id%>/pins" class="pin_it">Pin</a> -->
      <%=link_to 'Pin', user_post_pins_path(@post), {:class => 'pin_it',:method => :post}%>
    <%end%>
  <%end%>
</div>

app/views/users/show.html.erb
<div id="show">
<%= render partial: "posts/form", locals: {post: Post.new, destination: Destination.new}%>

</div>
<br></br><br>
<div class='container'>
    <div class='blog-posts'>
</div>
</div>
</div>